### ISSUE TITLE
Change `BreakoutAnalogInput` to `AnalogInput`

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix-bonsai-onix1#300]
This same change can be applied to `BreakoutAnalogOutput`, `BreakoutDigitalInput`, and `BreakoutDigitalOutput`. 

@jonnew mentioned this to me off-handedly that he doesn't like the current naming convention and I think it's worth discussing. It seems redundant, and I'm not sure what the benefit is.

**Comment by bparks13** [comment]
This change can actually be done for v0.3.0, since we are utilizing the `[Obsolete]` tag to not break workflows. Especially since we are still in a 0.y.z version and it is considered "unstable". The change that needs to be made for v1.0.0 would be to remove these obsolete classes entirely, since that would break workflows.

**Comment by bparks13** [comment]
@cjsha  Correct, they are not searchable, but if they exist in a workflow file they will be loaded correctly. Hence, this does not break existing workflows. There is a visual indicator that they might be obsolete, the color is correct but they do have cross-hatches. I linked an issue in the docs repo stating that we need to update the workflows to ensure that the SVGs on the website don't show this cross-hatching.
